angular.module("services",
[
    "services.rest",
    "services.cargo",
    "services.collections",
    "services.bestsellers",
    "services.payments",
    "services.fileReader",
    "services.authentication"
]);
